/* Content-hash cache busting for CSS, JS and images.
 *
 *   node src/assets.js          stamp every page with current asset hashes
 *   node src/assets.js --check  verify stamps are current, write nothing
 *
 * IN THIS KIT this is the only build step, and the lists below already
 * match the files the kit ships. Extend them as you add pages or scripts.
 *
 *   node src/assets.js          stamp every page with current hashes
 *   node src/assets.js --check  gate, before you deploy
 *
 * Why query strings rather than renamed files: the .min files are the sources
 * in this repo, they are served straight from disk, and renaming them on every
 * edit would mean the file you edit is never the file you shipped last time.
 * A ?v= stamp keeps one canonical name, leaves no orphaned old copies to prune,
 * and Cloudflare keys its cache on the full URL including the query string.
 *
 * The stamp is a hash of the file's bytes, never a hand-typed number: it
 * changes if and only if the content changed, so it cannot be forgotten and
 * cannot be bumped by accident. That matters because _headers serves these
 * paths as immutable for a year - shipping a stale URL is not recoverable by
 * purging Cloudflare, since the stale copy lives in the visitor's browser.
 */
const fs = require("fs");
const path = require("path");
const crypto = require("crypto");
const { execSync } = require("child_process");

/* The deploy directory. src/ and functions/ sit outside it and are never
   published, so nothing in them needs stamping. */
const ROOT = path.resolve(__dirname, "..", "public");

/* Every asset that _headers marks immutable AND that is referenced by URL in
   HTML. If you add one, add it here too, or it ships unstamped and gets cached
   for a year. An asset whose URL is assembled in JS instead belongs in
   JS_EMBEDDED below: stamp() rewrites markup and cannot see it. */
const ASSETS = [
  "css/style.min.css",
  "js/app.min.js",
  "js/ui.min.js",
];

/* Pages that carry asset references and are NOT generated by build.js.
   template.html is included so the generated homepages inherit the stamp. */
const PAGES = [
  "index.html",
  "contact.html",
  "privacy.html",
  "terms.html",
  "404.html",
];

function hashOf(rel) {
  const buf = fs.readFileSync(path.join(ROOT, rel));
  return crypto.createHash("sha1").update(buf).digest("hex").slice(0, 8);
}

function hashes() {
  const out = {};
  for (const a of ASSETS) out[a] = hashOf(a);
  return out;
}

/* Matches an asset URL with or without a stamp already on it, so running
   twice is a no-op rather than producing /css/style.min.css?v=aaa?v=bbb.
   The lookahead pins the match to a closing double quote - an HTML
   attribute and a JS string literal both end that way, which is what lets
   one matcher serve markup and source alike. */
function embedRe(rel) {
  const url = "/" + rel;
  return new RegExp(
    url.replace(/[.*+?^${}()|[\]\\]/g, "\\$&") + '(\\?v=[0-9a-f]+)?(?=")',
    "g"
  );
}

function stamp(html, h) {
  for (const a of ASSETS) html = html.replace(embedRe(a), "/" + a + "?v=" + h[a]);
  return html;
}

/* Source -> built file. The stamp check proves each page points at the file
   on disk; this proves the file on disk is what its source compiles to.
   Without it, editing src/app.js and forgetting terser passes every gate while
   the old widget stays live - the built file never changed, so its hash never
   changed, so nothing looked wrong. Only runs under --check: it shells out to
   terser three times, which is fine for a pre-push gate and wasteful in the
   normal stamping path. */
const BUILDS = [
  ["src/app.js", "js/app.min.js"],
  ["src/ui.js", "js/ui.min.js"],
];

const TERSER_FLAGS = "--compress --mangle --format comments=false";

function staleBuilds() {
  const repo = path.resolve(__dirname, "..");
  const out = [];
  for (const [src, built] of BUILDS) {
    const abs = path.join(ROOT, built);
    if (!fs.existsSync(abs)) { out.push(built + " (built file missing)"); continue; }
    let fresh;
    try {
      fresh = execSync("npx terser " + src + " " + TERSER_FLAGS, {
        cwd: repo, encoding: "utf8", maxBuffer: 8 << 20,
        stdio: ["ignore", "pipe", "pipe"],
      });
    } catch (e) {
      out.push(built + " (terser could not build " + src + ")");
      continue;
    }
    /* Compare on content only. terser writes no trailing newline to a file but
       adds one on stdout, and that difference is not drift. */
    const trim = (t) => String(t).replace(/\s+$/, "");
    if (trim(fresh) !== trim(fs.readFileSync(abs, "utf8"))) out.push(built);
  }
  return out;
}

/* Assets whose URL is assembled in JS at runtime, so stamp() - which rewrites
   HTML - can never reach them. The stamp is written into the SOURCE file and
   terser then carries it into the built file, which is what keeps staleBuilds()
   above satisfied: the built file really is what its source compiles to.

   The alternative is a hand-typed hash, which works right up until someone
   edits the CSS and forgets to bump it - and because _headers serves that path
   immutable for a year, forgetting is not recoverable by purging Cloudflare.
   Deriving it here means it cannot be forgotten.

   [source, built file, asset whose URL the source embeds] */
const JS_EMBEDDED = [
  ["src/app.js", "js/app.min.js", "css/widget.min.css"],
];

/* Writes the current hash into every source that embeds an asset URL, then
   rebuilds that source's .min file straight away - that has to happen before
   hashes() runs below, or the pages get stamped with the pre-rebuild hash of a
   file that is about to change. Returns the sources that were stale. */
function stampSources(write) {
  const repo = path.resolve(__dirname, "..");
  const stale = [];
  for (const [src, built, asset] of JS_EMBEDDED) {
    const abs = path.join(repo, src);
    if (!fs.existsSync(abs) || !fs.existsSync(path.join(ROOT, asset))) continue;
    const before = fs.readFileSync(abs, "utf8");
    const after = before.replace(embedRe(asset), "/" + asset + "?v=" + hashOf(asset));
    if (before === after) continue;
    stale.push(src);
    if (!write) continue;
    fs.writeFileSync(abs, after, "utf8");
    execSync("npx terser " + src + " " + TERSER_FLAGS + " -o public/" + built, {
      cwd: repo, stdio: ["ignore", "ignore", "pipe"],
    });
  }
  return stale;
}

const checkOnly = process.argv.includes("--check");

/* Before hashes(): this can rewrite a source and rebuild its .min file, which
   changes that built file's hash. */
const restamped = stampSources(!checkOnly);

const h = hashes();
let changed = 0;
const stale = [];

for (const p of PAGES) {
  const abs = path.join(ROOT, p);
  if (!fs.existsSync(abs)) continue;
  const before = fs.readFileSync(abs, "utf8");
  const after = stamp(before, h);
  if (before === after) continue;
  if (checkOnly) stale.push(p);
  else {
    fs.writeFileSync(abs, after, "utf8");
    changed++;
  }
}

if (checkOnly) {
  if (restamped.length) {
    console.error("  STALE WIDGET STAMP in: " + restamped.join(", "));
    console.error("  an asset changed but the URL built inside the JS still");
    console.error("  points at the old hash.");
    console.error("  run: node src/assets.js");
    process.exit(1);
  }
  if (stale.length) {
    console.error("  STALE STAMPS in: " + stale.join(", "));
    console.error("  run: node src/assets.js");
    process.exit(1);
  }
  const drifted = staleBuilds();
  if (drifted.length) {
    console.error("  STALE BUILD: " + drifted.join(", "));
    console.error("  the source changed but the minified file was not rebuilt.");
    for (const [src, built] of BUILDS) {
      if (drifted.some((d) => d.startsWith(built))) {
        console.error("  npx terser " + src + " " + TERSER_FLAGS + " -o public/" + built);
      }
    }
    console.error("  then: node src/assets.js");
    process.exit(1);
  }
  console.log("  asset stamps are current");
  console.log("  js-embedded asset urls are current");
  console.log("  built js matches src/");
  process.exit(0);
}

for (const a of ASSETS) {
  console.log("  " + a.padEnd(28) + "?v=" + h[a]);
}
for (const [src, , asset] of JS_EMBEDDED) {
  if (restamped.includes(src)) {
    console.log("  " + asset.padEnd(28) + "?v=" + hashOf(asset) + "  -> " + src + " (rebuilt)");
  }
}
console.log("");
console.log("  " + changed + " page(s) restamped");
